import { Gavel, ArrowRight, Wallet, CornerDownRight } from 'lucide-react';
import { maxBid } from '@/components/crack/engine';

export default function AuctionControls({ game, dispatch, visible = false }) {
  const a = game.auction, team = game.teams[a.turn], limit = maxBid(team);
  return <div className="auction-controls"><div className="eyebrow"><span className="pulse-dot" /> SUBASTA EN VIVO</div><h1>{visible ? <>¿Cuánto vale<br /><span>tu cálculo?</span></> : <>¿Cuánto vale<br /><span>tu intuición?</span></>}</h1><p className="muted">{visible ? 'La carta está a la vista. La decisión es toda tuya.' : 'La posición es la única pista. La decisión es tuya.'}</p><div className="current-bid"><div><span className="field-label">{a.leader === null ? 'PRECIO DE SALIDA' : 'MEJOR OFERTA'}</span><strong>{'$' + (a.price || 1)}<small>M</small></strong></div><div className="bid-owner">{a.leader === null ? <><Gavel size={20} /><span>Sin ofertas todavía</span></> : <><span className={'team-dot team-' + a.leader}><Gavel size={17} /></span><span>{game.teams[a.leader].team}<small>{game.teams[a.leader].name}</small></span></>}</div></div>
    <div className="turn-box" aria-live="polite"><div className="turn-heading"><span className={'team-dot team-' + a.turn}>{a.turn + 1}</span><div><span>LE TOCA A</span><h2>{team.name}</h2></div><span className="turn-team">{team.team}</span></div>{team.bot ? <p className="bot-turn-note"><span className="loading-ball" />El bot está pensando su oferta…</p> : <><div className="bid-buttons">{[1, 2, 5].map(amount => <button data-action={'bid-' + amount} key={amount} disabled={a.price + amount > limit} onClick={() => dispatch({ type: 'bid', amount })}><span>+{amount}M</span><small>{'Ofertar $' + (a.price + amount) + 'M'}</small></button>)}</div><button data-action="pass" className="pass-button" onClick={() => dispatch({ type: 'pass' })}>Pasar esta subasta <ArrowRight size={16} /></button><p className="reserve-note"><Wallet size={14} />{'Podés ofertar hasta $' + limit + 'M. Reservamos $' + (10 - team.squad.length) + 'M para completar tu once.'}</p></>}</div><p className="auction-note"><CornerDownRight size={14} />Si pasás, quedás afuera solo de esta subasta.</p>
  </div>;
}
