export default {
  "Rafael Márquez": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Rafael_M%C3%A1rquez.jpg/330px-Rafael_M%C3%A1rquez.jpg", "https://commons.wikimedia.org/wiki/File:Rafael_M%C3%A1rquez.jpg"],
  "Gabriel Mercado": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Gabriel_Mercado.jpg/330px-Gabriel_Mercado.jpg", "https://commons.wikimedia.org/wiki/File:Gabriel_Mercado.jpg"],
  "Ricardo Fort": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Ricardo_Fort.jpg/330px-Ricardo_Fort.jpg", "https://commons.wikimedia.org/wiki/File:Ricardo_Fort.jpg"],
  "Diego Placente": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Diego_Placente_2009.jpg/330px-Diego_Placente_2009.jpg", "https://commons.wikimedia.org/wiki/File:Diego_Placente_2009.jpg"],
  "Fabricio Coloccini": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Fabricio_Coloccini.jpg/330px-Fabricio_Coloccini.jpg", "https://commons.wikimedia.org/wiki/File:Fabricio_Coloccini.jpg"],
  "Lionel Scaloni": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Lionel_Scaloni_2022_vs_Colombia.jpg/330px-Lionel_Scaloni_2022_vs_Colombia.jpg", "https://commons.wikimedia.org/wiki/File:Lionel_Scaloni_2022_vs_Colombia.jpg"],
  "Marcos Acuña": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Marcos_Acu%C3%B1a.jpg/330px-Marcos_Acu%C3%B1a.jpg", "https://commons.wikimedia.org/wiki/File:Marcos_Acu%C3%B1a.jpg"],
  "Javier Milei": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Javier_Milei_VIVA_24.jpg/330px-Javier_Milei_VIVA_24.jpg", "https://commons.wikimedia.org/wiki/File:Javier_Milei_VIVA_24.jpg"],
  "Carlos Valderrama": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Carlos_Valderrama.jpg/330px-Carlos_Valderrama.jpg", "https://commons.wikimedia.org/wiki/File:Carlos_Valderrama.jpg"],
  "Clarence Seedorf": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Clarence_Seedorf_1_%284867567772%29.jpg/330px-Clarence_Seedorf_1_%284867567772%29.jpg", "https://commons.wikimedia.org/wiki/File:Clarence_Seedorf_1_%284867567772%29.jpg"],
  "Ricardo Bochini": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Ricardo_Bochini.jpg/330px-Ricardo_Bochini.jpg", "https://commons.wikimedia.org/wiki/File:Ricardo_Bochini.jpg"],
  "Esteban Cambiasso": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Argentine_-_Portugal_-_Esteban_Cambiasso.jpg/330px-Argentine_-_Portugal_-_Esteban_Cambiasso.jpg", "https://commons.wikimedia.org/wiki/File:Argentine_-_Portugal_-_Esteban_Cambiasso.jpg"],
  "Fernando Redondo": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Retrat_de_Fernando_Redondo.jpg/330px-Retrat_de_Fernando_Redondo.jpg", "https://commons.wikimedia.org/wiki/File:Retrat_de_Fernando_Redondo.jpg"],
  "Michael Laudrup": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Michael_Laudrup.jpg/330px-Michael_Laudrup.jpg", "https://commons.wikimedia.org/wiki/File:Michael_Laudrup.jpg"],
  "Jay-Jay Okocha": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Iffezheim-Rennplatz-212-Preis_der_Goenneranlage-Jay_Jay_Okocha_unter_Minarik-2008-gje.jpg/330px-Iffezheim-Rennplatz-212-Preis_der_Goenneranlage-Jay_Jay_Okocha_unter_Minarik-2008-gje.jpg", "https://commons.wikimedia.org/wiki/File:Iffezheim-Rennplatz-212-Preis_der_Goenneranlage-Jay_Jay_Okocha_unter_Minarik-2008-gje.jpg"],
  "Diego Simeone": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Diego_Simeone_-_01.jpg/330px-Diego_Simeone_-_01.jpg", "https://commons.wikimedia.org/wiki/File:Diego_Simeone_-_01.jpg"],
  "Éver Banega": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/%C3%89ver_Banega.jpg/330px-%C3%89ver_Banega.jpg", "https://commons.wikimedia.org/wiki/File:%C3%89ver_Banega.jpg"],
  "Guillermo Francella": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Guillermo_Francella_en_Premios_Platino_2023.jpg/330px-Guillermo_Francella_en_Premios_Platino_2023.jpg", "https://commons.wikimedia.org/wiki/File:Guillermo_Francella_en_Premios_Platino_2023.jpg"],
  "Sebastián Battaglia": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Battaglia_mar2015.jpg/330px-Battaglia_mar2015.jpg", "https://commons.wikimedia.org/wiki/File:Battaglia_mar2015.jpg"],
  "Bizarrap": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Bizarrap_ftt.jpg/330px-Bizarrap_ftt.jpg", "https://commons.wikimedia.org/wiki/File:Bizarrap_ftt.jpg"],
  "Samuel Eto’o": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Samuel_Eto%27o_April_2014.jpg/330px-Samuel_Eto%27o_April_2014.jpg", "https://commons.wikimedia.org/wiki/File:Samuel_Eto%27o_April_2014.jpg"],
  "Edinson Cavani": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Edinson_Cavani.jpg/330px-Edinson_Cavani.jpg", "https://commons.wikimedia.org/wiki/File:Edinson_Cavani.jpg"],
  "David Trezeguet": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Trezeguet_presentaci%C3%B3n_H%C3%A9rcules.jpg/330px-Trezeguet_presentaci%C3%B3n_H%C3%A9rcules.jpg", "https://commons.wikimedia.org/wiki/File:Trezeguet_presentaci%C3%B3n_H%C3%A9rcules.jpg"],
  "José Manuel Moreno": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Jos%C3%A9_Manuel_Moreno_en_1948.JPG/330px-Jos%C3%A9_Manuel_Moreno_en_1948.JPG", "https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Manuel_Moreno_en_1948.JPG"],
  "Enzo Francescoli": ["https://upload.wikimedia.org/wikipedia/commons/2/21/Enzo_Francescoli_2011.jpg", "https://commons.wikimedia.org/wiki/File:Enzo_Francescoli_2011.jpg"],
  "Markito Navaja": ["https://cloudfront-us-east-1.images.arcpublishing.com/infobae/P2EYN43CZFDALC4FWND3TE5FQM.jpg", "https://www.infobae.com/gaming/2020/11/21/markito-navaja-streamer-de-kru-creo-que-un-stream-copado-con-risas-y-con-buen-humor-te-cambia-el-dia/"],
  "Diego Forlán": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Diego_Forlan_against_Colombia.jpg/330px-Diego_Forlan_against_Colombia.jpg", "https://commons.wikimedia.org/wiki/File:Diego_Forlan_against_Colombia.jpg"],
  "Marcelo Tinelli": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Marcello_tinelli.jpg/330px-Marcello_tinelli.jpg", "https://commons.wikimedia.org/wiki/File:Marcello_tinelli.jpg"],
  "René Houseman": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Houseman_argentina_photo.jpg/330px-Houseman_argentina_photo.jpg", "https://commons.wikimedia.org/wiki/File:Houseman_argentina_photo.jpg"],
  "Claudio Caniggia": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Caniggia_sonriente_1988.jpg/330px-Caniggia_sonriente_1988.jpg", "https://commons.wikimedia.org/wiki/File:Caniggia_sonriente_1988.jpg"],
  "Ezequiel Lavezzi": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Ezequiel_Lavezzi.jpg/330px-Ezequiel_Lavezzi.jpg", "https://commons.wikimedia.org/wiki/File:Ezequiel_Lavezzi.jpg"],
  "Lucas Pratto": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Lucas_Pratto_01.jpg/330px-Lucas_Pratto_01.jpg", "https://commons.wikimedia.org/wiki/File:Lucas_Pratto_01.jpg"],
  "Lucas Janson": ["https://a.espncdn.com/photo/2023/0721/r1200360_1296x729_16-9.jpg", "https://www.espn.com.ar/futbol/argentina/nota/_/id/12337285/lucas-janson-revision-medica-para-firmar-con-boca-juniors"],
  "Momo": ["", ""],
  "Alejandro Domínguez": ["", ""],
  "Tung Tung Sahur": ["", ""]
};
